# Generated by Django 4.2.7 on 2023-11-13 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='post/')),
                ('description', models.TextField()),
                ('avantage', models.TextField()),
                ('certification', models.TextField()),
                ('auteur', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('prix', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('souscrire', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
