# Generated by Django 4.2.7 on 2023-11-14 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_domaine_emploi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploi',
            name='slug',
        ),
        migrations.AddField(
            model_name='emploi',
            name='poste',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emploi',
            name='image',
            field=models.ImageField(upload_to='emploi/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(upload_to='formation/'),
        ),
    ]
