# Generated by Django 4.2.7 on 2023-11-30 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0004_remove_emploi_slug_emploi_poste_alter_emploi_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('Amazone', 'amazone'), ('Alibaba', 'alibaba'), ('Ebay', 'ebay')], max_length=15)),
                ('lien', models.CharField(max_length=300)),
                ('adresse', models.CharField(max_length=100)),
                ('livraison', models.CharField(choices=[('En cours', 'en cours'), ('Livré', 'livré')], max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
