# Generated by Django 4.2.7 on 2023-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='achat',
            name='livraison',
            field=models.CharField(choices=[('en cours', 'En cours'), ('livré', 'Livré')], default='en cours', max_length=15),
        ),
        migrations.AlterField(
            model_name='achat',
            name='plateforme',
            field=models.CharField(choices=[('amazone', 'Amazone'), ('alibaba', 'Alibaba'), ('ebay', 'Ebay')], max_length=15),
        ),
    ]
